# NumPy Практикум: основы и примеры

## Цели:

- Освоить базовое создание и работу с массивами NumPy

- Понять индексацию/срезы, трансформации формы, broadcasting

- Научиться агрегировать и сортировать данные

- Работать со случайными числами, NaN и линейной алгеброй

Импорт и базовые настройки

In [1]:
import numpy as np

# Рекомендуется использовать новый генератор случайных чисел
rng = np.random.default_rng(seed=42)

# Красивый вывод чисел
np.set_printoptions(suppress=True, precision=3)

1. Создание массивов

In [2]:
# Из Python-списков
a = np.array([1, 2, 3], dtype=np.int64)
b = np.array([[1.0, 2.0], [3.5, 4.5]])  # dtype float автоматически
print(a, a.dtype)
print(b, b.dtype)

[1 2 3] int64
[[1.  2. ]
 [3.5 4.5]] float64


In [3]:
# Специальные конструкторы
z = np.zeros((2, 3))
o = np.ones((3, 2))
full = np.full((2, 2), fill_value=7)
eye = np.eye(4)              # единичная матрица
diag = np.diag([10, 20, 30]) # диагональная матрица

print(z)
print(o)
print(full)
print(eye)
print(diag)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [61]:
# Числовые последовательности
ar = np.arange(0, 10, 2)     # [0, 2, 4, 6, 8]
lin = np.linspace(0, 1, 5)   # 5 точек от 0 до 1 включительно
print(ar)
print(lin)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [62]:
# Случайные числа (новый API через Generator)
u = rng.random((2, 3))                 # U(0, 1)
n = rng.normal(loc=0, scale=1, size=5) # N(0, 1)
ri = rng.integers(0, 10, size=(2, 5))  # целые [0, 10)
print(u)
print(n)
print(ri)

[[0.774 0.439 0.859]
 [0.697 0.094 0.976]]
[ 0.128 -0.316 -0.017 -0.853  0.879]
[[1 9 7 6 4]
 [8 5 4 4 2]]


2. Атрибуты массива

In [63]:
x = rng.integers(0, 10, size=(3, 4))
print(x)
print("ndim:", x.ndim)     # число измерений
print("shape:", x.shape)   # форма
print("size:", x.size)     # количество элементов
print("dtype:", x.dtype)   # тип данных
print("itemsize:", x.itemsize, "байт на элемент")
print("nbytes:", x.nbytes, "всего байт")

[[0 5 8 0]
 [8 8 2 6]
 [1 7 7 3]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
itemsize: 8 байт на элемент
nbytes: 96 всего байт


3. Индексация, срезы, булевы и «фэнси»-индексация

In [64]:
y = np.arange(10)
print("y:", y)
print("y[0], y[-1]:", y[0], y[-1])
print("y[2:7:2]:", y[2:7:2])   # срез с шагом
print("y[::-1]:", y[::-1])     # разворот

y: [0 1 2 3 4 5 6 7 8 9]
y[0], y[-1]: 0 9
y[2:7:2]: [2 4 6]
y[::-1]: [9 8 7 6 5 4 3 2 1 0]


In [65]:
M = np.arange(1, 13).reshape(3, 4)
print("M:\n", M)
print("M[1, 2]:", M[1, 2])     # элемент
print("M[1, :]:", M[1, :])     # строка
print("M[:, 2]:", M[:, 2])     # столбец
print("Подматрица 2x2:\n", M[:2, :2])

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
M[1, 2]: 7
M[1, :]: [5 6 7 8]
M[:, 2]: [ 3  7 11]
Подматрица 2x2:
 [[1 2]
 [5 6]]


In [66]:
# Булевы маски
mask = M % 2 == 0
print("mask:\n", mask)
print("Только четные:\n", M[mask])

mask:
 [[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
Только четные:
 [ 2  4  6  8 10 12]


In [67]:
# Изменение по маске
M2 = M.copy()
M2[M2 < 5] = 0
print("M2:\n", M2)

M2:
 [[ 0  0  0  0]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [68]:
# Фэнси индексация (индексы-списки/массивы)
rows = [0, 2]
cols = [1, 3]
print("Выбор элементов М[rows, cols]:", M[rows, cols])  # (0,1) и (2,3)

Выбор элементов М[rows, cols]: [ 2 12]


In [69]:
# Виды vs копии:
a = np.arange(5)
view = a[::2]          # срез — представление (view)
view[0] = 999
print("a изменился через view:", a)

a изменился через view: [999   1   2   3   4]


In [70]:
copy_idx = a[[0, 2, 4]] # фэнси — копия
copy_idx[0] = -123
print("a не изменился через копию:", a)

a не изменился через копию: [999   1   2   3   4]


5. Агрегации и статистики

In [71]:
A = rng.integers(0, 10, size=(3, 4))
print("A:\n", A)
print("sum A:", A.sum())
print("sum по строкам:", A.sum(axis=1))
print("sum по столбцам:", A.sum(axis=0))
print("mean:", A.mean(), "std:", A.std(), "min:", A.min(), "max:", A.max())

A:
 [[0 9 4 8]
 [6 7 7 1]
 [3 4 4 0]]
sum A: 53
sum по строкам: [21 21 11]
sum по столбцам: [ 9 20 15  9]
mean: 4.416666666666667 std: 2.9285472318009296 min: 0 max: 9


In [72]:
# Индексы экстремумов
print("argmax flat:", A.argmax(), "-> индекс в форме:", np.unravel_index(A.argmax(), A.shape))
print("argmax по столбцам:", A.argmax(axis=0))
print("percentile 90:", np.percentile(A, 90))

argmax flat: 1 -> индекс в форме: (np.int64(0), np.int64(1))
argmax по столбцам: [1 0 1 0]
percentile 90: 7.9


4. Арифметика, ufunc и broadcasting


In [73]:
p = np.array([1, 2, 3])
q = np.array([10, 20, 30])

print("Сложение/вычитание:", p + q, p - q)
print("Умножение поэлементно:", p * q)
print("Деление поэлементно:", q / p)
print("Степень:", p ** 2)

Сложение/вычитание: [11 22 33] [ -9 -18 -27]
Умножение поэлементно: [10 40 90]
Деление поэлементно: [10. 10. 10.]
Степень: [1 4 9]


In [74]:
# Ufunc (универсальные функции) — поэлементные
r = np.linspace(-2, 2, 5)
print("r:", r)
print("exp(r):", np.exp(r))
print("log(|r|+1):", np.log(np.abs(r) + 1))
print("sin(r):", np.sin(r))

r: [-2. -1.  0.  1.  2.]
exp(r): [0.135 0.368 1.    2.718 7.389]
log(|r|+1): [1.099 0.693 0.    0.693 1.099]
sin(r): [-0.909 -0.841  0.     0.841  0.909]


In [75]:
# np.where — условное поэлементное ветвление
relu = np.where(r > 0, r, 0)
print("ReLU(r):", relu)

ReLU(r): [0. 0. 0. 1. 2.]


In [76]:
# Broadcasting: вычитание среднего из столбцов
X = rng.normal(size=(4, 3))
col_means = X.mean(axis=0)         # shape (3,)
X_centered = X - col_means         # (4, 3) - (3,) = (4, 3)
print("X:\n", X)
print("col_means:", col_means)
print("X_centered:\n", X_centered)

X:
 [[ 0.413  0.431  2.142]
 [-0.406 -0.512 -0.814]
 [ 0.616  1.129 -0.114]
 [-0.84  -0.824  0.651]]
col_means: [-0.054  0.056  0.466]
X_centered:
 [[ 0.467  0.375  1.676]
 [-0.352 -0.568 -1.28 ]
 [ 0.67   1.073 -0.58 ]
 [-0.786 -0.88   0.184]]


In [77]:
# Пример с добавлением осей
a = np.arange(3).reshape(3, 1)     # shape (3,1)
b = np.arange(4).reshape(1, 4)     # shape (1,4)
print("a + b (broadcast до 3x4):\n", a + b)

a + b (broadcast до 3x4):
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


6. Изменение формы, транспонирование, конкатенация

In [78]:
B = np.arange(12)
print("B:", B)
print("reshape 3x4:\n", B.reshape(3, 4))
print("ravel (view если возможно):", B.reshape(3,4).ravel())
print("flatten (всегда копия):", B.reshape(3,4).flatten())

B: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ravel (view если возможно): [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten (всегда копия): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [79]:
C = np.arange(6).reshape(2, 3)
print("C:\n", C)
print("C.T:\n", C.T)
print("swapaxes 0<->1:\n", np.swapaxes(C, 0, 1))

C:
 [[0 1 2]
 [3 4 5]]
C.T:
 [[0 3]
 [1 4]
 [2 5]]
swapaxes 0<->1:
 [[0 3]
 [1 4]
 [2 5]]


In [80]:
# Склейки и разбиения
X1 = np.arange(6).reshape(2, 3)
X2 = np.arange(100, 106).reshape(2, 3)
print("concatenate по оси 1:\n", np.concatenate([X1, X2], axis=1))
print("vstack:\n", np.vstack([X1, X2]))
print("hstack:\n", np.hstack([X1, X2]))

concatenate по оси 1:
 [[  0   1   2 100 101 102]
 [  3   4   5 103 104 105]]
vstack:
 [[  0   1   2]
 [  3   4   5]
 [100 101 102]
 [103 104 105]]
hstack:
 [[  0   1   2 100 101 102]
 [  3   4   5 103 104 105]]


In [81]:
Y = np.arange(10)
print("split на 3 части:", np.array_split(Y, 3))  # части могут быть неравными

split на 3 части: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [82]:
# repeat и tile
v = np.array([1, 2, 3])
print("repeat элементов:", np.repeat(v, [1, 2, 3]))  # [1, 2,2, 3,3,3]
print("tile в 2 строки:\n", np.tile(v, (2, 1)))

repeat элементов: [1 2 2 3 3 3]
tile в 2 строки:
 [[1 2 3]
 [1 2 3]]


7. Работа с NaN и Inf

In [83]:
W = np.array([1.0, np.nan, 2.0, np.inf, -np.inf])
print("W:", W)
print("isnan:", np.isnan(W))
print("isfinite:", np.isfinite(W))

W: [  1.  nan   2.  inf -inf]
isnan: [False  True False False False]
isfinite: [ True False  True False False]


In [84]:
W = np.array([1.0, np.nan, 2.0])
# nan-версии агрегатов игнорируют NaN
print("mean с NaN:", np.mean(W))       # будет nan
print("nanmean:", np.nanmean(W))       # игнорирует NaN

mean с NaN: nan
nanmean: 1.5


In [85]:
# Замена NaN на среднее
Z = rng.normal(size=(5, 3))
mask = rng.random((5, 3)) < 0.3
Z[mask] = np.nan
col_means = np.nanmean(Z, axis=0)
Z_filled = np.where(np.isnan(Z), col_means, Z)
print("Z с NaN:\n", Z)
print("Z без NaN:\n", Z_filled)

Z с NaN:
 [[ 0.743    nan    nan]
 [ 0.232  0.117  0.219]
 [ 0.871  0.224  0.679]
 [ 0.068  0.289    nan]
 [-1.457    nan -0.47 ]]
Z без NaN:
 [[ 0.743  0.21   0.142]
 [ 0.232  0.117  0.219]
 [ 0.871  0.224  0.679]
 [ 0.068  0.289  0.142]
 [-1.457  0.21  -0.47 ]]


8. Случайные числа: выборки и перестановки

In [86]:
rng = np.random.default_rng(123)     # фиксируем сид для воспроизводимости

# Перестановка и выборка
arr = np.arange(10)
print("перемешанный arr:", rng.permutation(arr))
print("выбор 5 элементов без возвращения:", rng.choice(arr, size=5, replace=False))
print("выбор с весами:", rng.choice(arr, size=5, p=np.repeat(0.1, 10)))

# Простая симуляция: 100 бросков игрального кубика
dice = rng.integers(1, 7, size=100)
print("среднее значение кубика:", dice.mean())

перемешанный arr: [7 4 0 2 1 5 6 8 3 9]
выбор 5 элементов без возвращения: [4 3 7 2 8]
выбор с весами: [5 2 8 2 7]
среднее значение кубика: 3.37


9. Линейная алгебра

In [87]:
# Вектор-матрица-умножение
A = rng.normal(size=(3, 3))
x = rng.normal(size=3)
y = A @ x  # эквивалент np.dot(A, x)
print("A:\n", A)
print("x:", x)
print("A @ x:", y)

A:
 [[-0.461 -1.436  1.365]
 [ 0.439 -0.712  0.297]
 [-0.438 -0.212  0.364]]
x: [0.953 1.52  1.704]
A @ x: [-0.295 -0.157 -0.119]


In [88]:
# Решение линейной системы A x = b
b = rng.normal(size=3)
sol = np.linalg.solve(A, b)
residual = np.linalg.norm(A @ sol - b)
print("Решение:", sol, "Остаток:", residual)

Решение: [0.301 1.524 1.522] Остаток: 1.7772239894833365e-16


In [89]:
# Собственные значения (для квадратной матрицы)
w, V = np.linalg.eig(A)
print("Собственные значения:", w)

Собственные значения: [-0.384+1.007j -0.384-1.007j -0.039+0.j   ]


In [90]:
# Нормы
print("||x||_2:", np.linalg.norm(x), "||A||_F:", np.linalg.norm(A, 'fro'))

||x||_2: 2.4739446866348005 ||A||_F: 2.301222789081471


10. Сортировка, argsort и top-k

In [91]:
S = rng.integers(0, 100, size=12)
print("S:", S)
print("отсортировано:", np.sort(S))
print("индексы сортировки:", np.argsort(S))

S: [88 75 95  7 17 48 85 30 29 84  0 95]
отсортировано: [ 0  7 17 29 30 48 75 84 85 88 95 95]
индексы сортировки: [10  3  4  8  7  5  1  9  6  0  2 11]


In [92]:
# Быстрый top-k (порядок внутри k не гарантирован)
k = 3
idx_topk = np.argpartition(S, -k)[-k:]
topk_values = S[idx_topk]
# Если нужно отсортировать убыванием:
topk_sorted_idx = idx_topk[np.argsort(S[idx_topk])[::-1]]
print("top-3 значения:", S[topk_sorted_idx], "индексы:", topk_sorted_idx)

top-3 значения: [95 95 88] индексы: [11  2  0]


11. Ввод/вывод

In [93]:
data = rng.normal(size=(3, 4))
np.save("data.npy", data)          # бинарный формат .npy
loaded = np.load("data.npy")
print("Загрузка .npy эквивалентна исходным данным:", np.allclose(data, loaded))

Загрузка .npy эквивалентна исходным данным: True


In [94]:
# Несколько массивов в одном файле
np.savez("pack.npz", a=data, b=data*2)
pack = np.load("pack.npz")
print("Ключи в npz:", list(pack.keys()))
print("pack['b']:\n", pack["b"])

Ключи в npz: ['a', 'b']
pack['b']:
 [[-1.296 -0.567 -1.99  -0.546]
 [ 0.845 -0.163  2.469  0.302]
 [ 0.962 -0.298  2.631 -2.445]]


In [95]:
# Текстовые файлы (внимание на скорость/точность)
np.savetxt("data.txt", data, fmt="%.5f")
loaded_txt = np.loadtxt("data.txt")
print("Сравнение с текстом:", np.allclose(data, loaded_txt))

Сравнение с текстом: False


12. Производительность: векторизация vs Python-цикл


In [96]:
# Задача: посчитать y = x^2 + 2x + 1 для 10 млн элементов
N = 1_000_000
x = rng.random(N)

# Векторизованный вариант
def poly_vec(x):
    return x*x + 2*x + 1

# Невекторизованный (цикл Python) — медленно
def poly_loop(x):
    out = np.empty_like(x)
    for i in range(x.size):
        out[i] = x[i]*x[i] + 2*x[i] + 1
    return out

# В Jupyter можно использовать магию %%timeit
# Здесь просто проверим корректность
y_vec = poly_vec(x)
y_loop = poly_loop(x)
print("Проверка равенства:", np.allclose(y_vec, y_loop))

Проверка равенства: True


In [97]:
%%timeit -n 10 -r 3
_ = poly_vec(x)

9.82 ms ± 155 µs per loop (mean ± std. dev. of 3 runs, 10 loops each)


In [98]:
%%timeit -n 1 -r 3
_ = poly_loop(x)

592 ms ± 6.43 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)


## Задания для самостоятельной работы (10 задач с ростом сложности)

1. Базовые конструкторы, reshape и индексация

Создайте массив от 0 до 15 включительно.\
Преобразуйте его в матрицу 4x4.\
Поменяйте местами 2-ю и 4-ю строки, затем 1-й и 3-й столбцы (без циклов).

In [6]:
array_1 = np.arange(0, 16)
array_1 = array_1.reshape(4, 4)
array_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
# Меняем местами 2-ю и 4-ю строки (индексы 1 и 3)
array_1[[1, 3]] = array_1[[3, 1]]
print("\nМатрица после смены 2-й и 4-й строк:")
print(array_1)

# Меняем местами 1-й и 3-й столбцы (индексы 0 и 2)
array_1[:, [0, 2]] = array_1[:, [2, 0]]
print("\nМатрица после смены 1-го и 3-го столбцов:")
print(array_1)


Матрица после смены 2-й и 4-й строк:
[[ 0  1  2  3]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]]

Матрица после смены 1-го и 3-го столбцов:
[[ 2  1  0  3]
 [14 13 12 15]
 [10  9  8 11]
 [ 6  5  4  7]]


2. Шахматная доска

Создайте массив 8x8 со значениями 0 и 1 в шахматном порядке.\
Верхний левый элемент должен быть 1.

In [8]:
array_2 = np.zeros((8, 8))
for i in range(64):
    row = i // 8
    col = i % 8
    if (row + col) % 2 == 0:
        array_2[row, col] = 1

array_2

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

3. Булева маска и замена

Дан a = np.arange(1, 101).\
Получите массив квадратов только для элементов, кратных 3 или 5, а остальные замените на -1 (используйте np.where или маски).

In [11]:
a = np.arange(1, 101)
a_new = a.copy()

a_new = np.where((a_new % 5 == 0) | (a_new % 3 == 0), a_new * a_new, -1)
a_new

array([   -1,    -1,     9,    -1,    25,    36,    -1,    -1,    81,
         100,    -1,   144,    -1,    -1,   225,    -1,    -1,   324,
          -1,   400,   441,    -1,    -1,   576,   625,    -1,   729,
          -1,    -1,   900,    -1,    -1,  1089,    -1,  1225,  1296,
          -1,    -1,  1521,  1600,    -1,  1764,    -1,    -1,  2025,
          -1,    -1,  2304,    -1,  2500,  2601,    -1,    -1,  2916,
        3025,    -1,  3249,    -1,    -1,  3600,    -1,    -1,  3969,
          -1,  4225,  4356,    -1,    -1,  4761,  4900,    -1,  5184,
          -1,    -1,  5625,    -1,    -1,  6084,    -1,  6400,  6561,
          -1,    -1,  7056,  7225,    -1,  7569,    -1,    -1,  8100,
          -1,    -1,  8649,    -1,  9025,  9216,    -1,    -1,  9801,
       10000])

4. Объединение и разбиение

Сгенерируйте два массива X1 и X2 размерностями (5, 3) из N(0,1).\
Склейте их по вертикали, затем разделите обратно на две части без копирования данных, если это возможно.\
Подсказка: обратите внимание на то, какие операции создают представления (view), а какие — копии.

In [14]:
X1 = rng.normal(loc=0, scale=1, size=5)
X2 = rng.normal(loc=0, scale=1, size=5)
 
X1

array([0.879, 0.778, 0.066, 1.127, 0.468])

In [15]:
result = np.concatenate([X1, X2], axis=0)
result

array([ 0.879,  0.778,  0.066,  1.127,  0.468, -0.859,  0.369, -0.959,
        0.878, -0.05 ])

In [16]:
X1_new, X2_new = np.array_split(result, 2)
X1_new

array([0.879, 0.778, 0.066, 1.127, 0.468])

5. Нормализация по столбцам (broadcasting)

Сгенерируйте матрицу X (100 x 3) из N(0, 5).\
Приведите каждый столбец к нулевому среднему и единичному стандартному отклонению.\
Проверьте, что среднее каждой колонки ~ 0 и std ~ 1.

In [17]:
X = rng.normal(loc=0, scale=np.sqrt(5), size=(100, 3))
X_standardized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
X_standardized

array([[-0.128, -0.746,  1.261],
       [-0.095, -0.476, -0.361],
       [ 0.658,  0.372,  0.427],
       [ 0.547,  2.269, -0.417],
       [-0.487, -0.887,  0.636],
       [ 1.312, -0.14 , -0.864],
       [-0.829,  0.677,  0.767],
       [ 0.67 , -0.729,  0.241],
       [ 0.202,  0.215,  0.899],
       [ 0.32 ,  0.707,  0.071],
       [ 0.391,  0.656, -1.499],
       [-0.276, -0.521, -0.656],
       [-0.227,  1.579, -0.89 ],
       [ 1.135, -1.816, -0.343],
       [ 0.253,  0.608,  0.734],
       [ 0.944, -0.391, -0.475],
       [ 1.015, -0.223, -1.312],
       [-1.167, -1.   ,  0.514],
       [ 0.231,  0.719, -0.438],
       [ 0.248,  0.65 , -0.317],
       [ 0.575, -0.725, -0.372],
       [-0.344, -1.296,  0.503],
       [-0.44 , -0.005,  0.497],
       [ 0.564,  0.692, -0.1  ],
       [-0.389, -0.103, -1.736],
       [-1.511, -1.431, -1.025],
       [ 0.513, -0.985, -0.388],
       [ 1.498, -0.399,  0.761],
       [-0.948, -0.238, -0.977],
       [-0.297,  0.879, -1.777],
       [ 0

In [18]:
means = np.mean(X_standardized, axis=0)
stds = np.std(X_standardized, axis=0)

print("Средние значения по столбцам (должны быть ~0):")
print(means)
print("\nСтандартные отклонения по столбцам (должны быть ~1):")
print(stds)

Средние значения по столбцам (должны быть ~0):
[-0. -0.  0.]

Стандартные отклонения по столбцам (должны быть ~1):
[1. 1. 1.]


6. Попарные расстояния (без циклов)

Дан вектор v длины N. Постройте матрицу D (N x N), где D[i, j] = |v[i] - v[j]|, используя broadcasting (без явных Python-циклов).\
Дополнительно: то же для квадратов разностей.

In [23]:
N = int(input())
v = np.arange(1, N+1)

v_col = v.reshape(N, 1)  # Столбец (N x 1)
v_row = v.reshape(1, N)  # Строка (1 x N)

# Матрица абсолютных разностей: D[i, j] = |v[i] - v[j]|
D_abs = np.abs(v_col - v_row)

# Матрица квадратов разностей: D[i, j] = (v[i] - v[j]) ** 2
D_sq = (v_col - v_row) ** 2

In [24]:
print("Вектор v:")
print(v)
print("\nМатрица абсолютных разностей D_abs:")
print(D_abs)
print("\nМатрица квадратов разностей D_sq:")
print(D_sq)

Вектор v:
[1 2 3 4]

Матрица абсолютных разностей D_abs:
[[0 1 2 3]
 [1 0 1 2]
 [2 1 0 1]
 [3 2 1 0]]

Матрица квадратов разностей D_sq:
[[0 1 4 9]
 [1 0 1 4]
 [4 1 0 1]
 [9 4 1 0]]


7. Монте-Карло оценка числа π

Сгенерируйте N пар (x, y) из U(-1, 1).\
Оцените π как 4 * (доля точек внутри единичного круга).\
Исследуйте зависимость погрешности от N (напр., N = 10^3, 10^4, 10^5)

In [27]:
# Значения N для исследования
Ns = [10**3, 10**4, 10**5]

results = {}

for N in Ns:
    # Генерация N пар (x, y) из U(-1, 1)
    x = np.random.uniform(-1, 1, N)
    y = np.random.uniform(-1, 1, N)
    
    # Проверка точек внутри круга
    inside = (x**2 + y**2) <= 1
    count_inside = np.sum(inside)
    
    # Оценка π
    pi_est = 4 * (count_inside / N)
    
    # Погрешность
    error = np.abs(pi_est - np.pi)
    
    results[N] = {'pi_estimate': pi_est, 'error': error}

# Вывод результатов
print(results)

{1000: {'pi_estimate': np.float64(3.168), 'error': np.float64(0.026407346410207033)}, 10000: {'pi_estimate': np.float64(3.1328), 'error': np.float64(0.008792653589793087)}, 100000: {'pi_estimate': np.float64(3.15112), 'error': np.float64(0.009527346410207027)}}


8. Топ-частоты значений

Сгенерируйте массив целых чисел длины 100000 из диапазона [0, 999].\
Найдите 5 самых частых значений и их частоты (используйте np.unique(return_counts=True) и argsort/argpartition).\
Верните значения, частоты и долю этих значений от общего числа.

In [34]:
array_8 = rng.integers(0, 999, size=100000)

In [35]:
# Создать уникальный массив и подсчитать массив

unique_array,count_array = np.unique(array_8, return_counts = True)

# Распечатать значения уникального массива и обратного массива
top_indices = np.argsort(count_array)[-5:][::-1]
top_values = unique_array[top_indices]
top_counts = count_array[top_indices]

# Доля частых значений от всех чисел в массиве
print("5 самых частых значений:", top_values)
print("Их частоты:", top_counts)
print("Доля частых значений от всех чисел в массиве:", top_counts / array_8.size)

5 самых частых значений: [970  34 662 453 264]
Их частоты: [133 132 129 128 128]
Доля частых значений от всех чисел в массиве: [0.001 0.001 0.001 0.001 0.001]


9. Работа с пропусками

Сгенерируйте матрицу X (200 x 5) из N(0,1). С вероятностью 10% замените элементы на NaN.\
Замените NaN средним по соответствующему столбцу (без циклов).\
Проверьте, что NaN больше не осталось, и что средние по столбцам не изменились для строк без NaN.

In [37]:
array_9 = rng.normal(loc=0, scale=1, size=(200, 5)) # N(0, 1)
# С вероятностью 10% замените элементы на NaN
mask = rng.random(array_9.shape) < 0.1
array_9[mask] = np.nan

array_9

array([[ 1.623,    nan, -1.239,  1.876,  2.186],
       [ 0.478,  0.137, -0.062, -0.219, -1.248],
       [ 0.827, -0.943,  0.653,    nan,  1.095],
       [-0.686, -1.276, -1.012, -0.022, -0.155],
       [-1.282, -0.533,  0.079,    nan, -0.023],
       [ 0.702,  0.042,  0.048,  0.5  , -1.192],
       [ 1.887,    nan, -0.088,  0.249,  1.139],
       [ 0.416,  0.637,  0.089, -1.081, -2.596],
       [ 0.83 ,  1.009, -1.198, -1.317, -1.171],
       [-0.641, -0.955,  0.076,  0.109,    nan],
       [-0.589, -0.978, -1.552, -0.65 ,    nan],
       [-1.702, -0.151, -1.14 , -1.383,  0.885],
       [ 1.152,  0.42 ,    nan,  0.758,  0.666],
       [ 1.923, -0.608,  0.302,    nan, -1.973],
       [-1.905, -0.013, -0.812,  0.451,  0.578],
       [   nan, -1.616, -1.051,  0.172,  0.273],
       [ 0.287,  0.803, -0.304,  0.147,  0.495],
       [ 0.905,    nan, -0.111,  0.245, -0.016],
       [-0.335, -0.697, -1.781,  0.472,  0.402],
       [ 0.201,  0.348, -0.228,  1.809,    nan],
       [   nan, -0.7

In [38]:
col_means = np.nanmean(array_9, axis=0)
array_9_filled = np.where(np.isnan(array_9), col_means, array_9)
# Проверьте, что NaN больше не осталось, и что средние по столбцам не изменились для строк без NaN.
print("Проверка на наличие NaN:", np.isnan(array_9_filled).any())
print("Средние по столбцам до заполнения NaN:", np.nanmean(array_9, axis=0))
print("Средние по столбцам после заполнения NaN:", np.mean(array_9_filled, axis=0))

Проверка на наличие NaN: False
Средние по столбцам до заполнения NaN: [ 0.052  0.034 -0.004 -0.002  0.013]
Средние по столбцам после заполнения NaN: [ 0.052  0.034 -0.004 -0.002  0.013]


10. PCA через SVD

Сгенерируйте матрицу X (200 x 10) из N(0,1), центрируйте по столбцам.\
Выполните SVD: X = U S Vt.\
Оставьте первые k=2 компоненты, постройте приближение X2 = U[:, :2] @ diag(S[:2]) @ Vt[:2, :].\
Оцените долю объясненной дисперсии и среднеквадратичную ошибку между X и X2.

In [39]:
# 1. Генерация матрицы X (200 x 10) из N(0,1)
X = rng.normal(loc=0, scale=1, size=(200, 10))

# 2. Центрирование по столбцам
X_centered = X - np.mean(X, axis=0)

# 3. Выполнение SVD
U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)

# 4. Оставляем первые k=2 компоненты и строим приближение X2
k = 2
U_k = U[:, :k]  # Первые k столбцов U
S_k = S[:k]     # Первые k сингулярных значений
Vt_k = Vt[:k, :] # Первые k строк Vt
X2 = U_k @ np.diag(S_k) @ Vt_k  # Приближение X2

X2

array([[ 0.558, -0.11 , -0.594, ...,  0.544, -0.537,  0.345],
       [-0.483,  0.096,  0.516, ..., -0.472,  0.466, -0.299],
       [ 0.582, -0.023, -0.041, ...,  0.235, -0.021,  0.251],
       ...,
       [-0.098,  0.096,  0.592, ..., -0.375,  0.548, -0.151],
       [-0.616,  0.01 , -0.049, ..., -0.196, -0.064, -0.249],
       [ 0.109, -0.072, -0.435, ...,  0.289, -0.402,  0.127]])

In [40]:
# 5. Оценка доли объясненной дисперсии
explained_variance_ratio = np.sum(S_k**2) / np.sum(S**2)

# 6. Среднеквадратичная ошибка (RMSE)
mse = np.mean((X_centered - X2)**2)
rmse = np.sqrt(mse)

# Вывод результатов
print("Доля объясненной дисперсии (для k=2):", explained_variance_ratio)
print("Среднеквадратичная ошибка (RMSE):", rmse)

Доля объясненной дисперсии (для k=2): 0.263237455154392
Среднеквадратичная ошибка (RMSE): 0.8532850516499745
